version: '3.7'


services:
  api-solid-findafriend:
    image: bitnami/postgresql
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apifindafriend
